name: 'Terraform'

on:
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    #  defaults:
    #    run:
    #      shell: bash
    #      working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Prerequisites
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip" --output terraform.zip
          unzip "terraform.zip"
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip

      - name: Install Terraform Lint (TFLint)
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          unzip tflint_linux_amd64
          mv tflint /usr/local/bin
  #        curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | egrep -v 'rc|beta|alpha' | egrep 'linux.*amd64'  | tail -1 --output terraform.zip
